server:
  tomcat:
    basedir: /tmp/dir
web:
  host-url: http://scmp.bms.aiqin.com
center:
  main:
  #中控服务端
    url: http://control.api.aiqin.com
    #url: http://39.106.215.2:9003
  #中控前端
    host: http://control.mgs.aiqin.com
product:
  info:
    url: http://com.aiqin.bms.scmp.api.api.aiqin.com
ground:
  druid:
    url: jdbc:mysql://rm-2zeela0dj4k34987s.mysql.rds.aliyuncs.com/mgs_supplier_release?connectTimeout=5000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: supplier_write
    password: D80SjZXnBLJxZLEZyf(x)vi
oss:
  end:
    point: http://oss-cn-qingdao.aliyuncs.com
  access:
    key:
      id: LTAIPWfI0ApMnQPo
      secret: kG0tvYo3Ts4tr95sa9eh3Pw3wF2WQ7
  bucket:
    name: lyj-upload-image
  dir: dev/

Encryption:
  key: 16#t%9@AJ6DYaeRp
#  dZ3@k!KMhq!Tqeh3%RYm83cX&JmvYyY!
UserName:
  key: 11921
CurrentPositionCode:
  key: GW00566


