server:
  port: 8081
spring:
  profiles:
    active: ${profile.name}
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  swagger:
    enabled: true
    title: SUPPLIER-API
    description: 熙耘供应链系统的API文档
    version: 1.0.0
    contact:
      name: liuxiaohan
    base-package: com.aiqin.bms.scmp.api.webSwagger2Config
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
control:
  url:
   # 角色列表
    role-list: http://control.api.aiqin.com/role/list
    # 角色绑定
    role-add: http://control.api.aiqin.com/person/account/role
   # 主控增加人员等接口
    account: http://control.api.aiqin.com/external/account
mybatis:
  mapper-locations: classpath*:/com/aiqin/bms/scmp/api/*/dao/*.xml,classpath*:/com/aiqin/bms/scmp/api/*/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.aiqin.bms.scmp.api.*.domain
  configuration:
    call-setters-on-nulls: true
logging:
  config: classpath:logback.xml
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
activiti:
  host: http://flows.aiqin.com
marker:
  info:
    url: http://market.api.aiqin.com/
Central:
  url: http://control.api.aiqin.com
Store:
  url: http://store.api.aiqin.com
Workflow:
  url: http://finance.bms.aiqin.com/tpm/workflowcontroller/submit
  cancelUrl: http://finance.bms.aiqin.com/tpm/workflowcontroller/cancel
#审批流的前缀url地址
WorkFlowBaseUrl:
  #回调url
  callBackBaseUrl: http://scmp.api.aiqin.com/workFlow/workFlowCallBack/
  #各个页面详情url
  supplierUrl:
    #合同申请详情
    applyContract: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
    #供应商申请详情
    applySupplier: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
    #供应商集团申请详情
    applySupplierGroup: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
    #供应商账户申请详情
    applySupplierAccount: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
  productUrl:
    #变价
    variablePrice: http://scmp.bms.aiqin.com/#/price/detailIntending
    #sku
    applySku: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
    #sku配置
    applySkuConfig: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
    #销售区域
    applySaleArea: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
    #调拨申请详情
    applyAllocattion: http://scmp.bms.aiqin.com/#/store/detailTransfer
    #移库查看详情
    movement: http://scmp.bms.aiqin.com/#/store/detailMove
    #报废
    scrap: http://scmp.bms.aiqin.com/#/store/detailScrap
  purchaseUrl:
    #采购申请详情
    applyPurchase: http://scmp.bms.aiqin.com/#/purchase/detailPurchase
    #退供申请详情
    applyRefund: http://scmp.bms.aiqin.com/#/purchase/returnDetail
#审批流的host
WorkFlowBaseHost:
  supplierHost: http://scmp.bms.aiqin.com
#不拦截的公参
BaseParam:
  authority: authority=0
WMS:
  url: http://39.96.81.67:9003
order:
  info:
    url: http://order.api.aiqin.com/
mgs:
  control:
    system-code: scmp-system
    center: http://control.api.aiqin.com/system/plan
    resources:
    - code: SCMP001
      name: 审批管理
      link: '/approve/list'
      icon: icon-aq-shenpi
    - code: SCMP002
      name: 基础资料管理
      link: ''
      icon: icon-aq-jichuziliao
      resources:
      - code: SCMP002001
        name: 字典管理
        link: '/basicData/dictionary'
      - code: SCMP002002
        name: 采购组管理
        link: '/basicData/purchasingGroup'
      - code: SCMP002003
        name: 仓库管理
        link: '/basicData/store'
      - code: SCMP002004
        name: 库房管理
        link: '/basicData/warehouse'
      - code: SCMP002005
        name: 价格项目管理
        link: '/basicData/priceProject'
      - code: SCMP002006
        name: 渠道管理
        link: '/basicData/channel'
      - code: SCMP002007
        name: 标签管理
        link: '/basicData/label'
      - code: SCMP002008
        name: 规则管理
        link: '/basicData/rules'
      - code: SCMP002009
        name: 促销SKU管理
        link: '/basicData/promoteSku'
    - code: SCMP003
      name: 供应商管理
      link: ''
      icon: icon-aq-gongyingshang
      resources:
      - code: SCMP003001
        name: 供应商集团管理
        link: '/supplier/supplierGroup'
        methods:
        - code: SCMP003001001
          name: 新增
        - code: SCMP003001002
          name: 编辑
        - code: SCMP003001003
          name: 审批跟踪
      - code: SCMP003002
        name: 供应商管理
        link: '/supplier/supplier'
        methods:
        - code: SCMP003002001
          name: 新增
        - code: SCMP003002002
          name: 编辑
        - code: SCMP003002003
          name: 待申请
        - code: SCMP003002004
          name: 审批跟踪
      - code: SCMP003003
        name: 供应商合同管理
        link: '/supplier/contract'
        methods:
        - code: SCMP003003001
          name: 新增
        - code: SCMP003003002
          name: 编辑
        - code: SCMP003003003
          name: 审批跟踪
      - code: SCMP003004
        name: 供应商结算账户管理
        link: '/supplier/account'
        methods:
        - code: SCMP003004001
          name: 新增
        - code: SCMP003004002
          name: 编辑
        - code: SCMP003004003
          name: 审批跟踪
      - code: SCMP003005
        name: 供应商账号管理
        link: '/basicData/accountList'
        methods:
        - code: SCMP003005001
          name: 新增
        - code: SCMP003005002
          name: 编辑
      - code: SCMP003006
        name: 供应商评分管理
        link: '/supplier/rate'
        methods:
        - code: SCMP003006001
          name: 新增
      - code: SCMP003007
        name: 制造商管理
        link: '/supplier/manufacturer'
        methods:
        - code: SCMP003007001
          name: 新增
        - code: SCMP003007002
          name: 编辑
        - code: SCMP003007003
          name: 禁用
    - code: SCMP004
      name: 商品管理
      link: ''
      icon: icon-aq-shangping
      resources:
      - code: SCMP004001
        name: 品类管理
        link: '/product/category'
        methods:
        - code: SCMP004001001
          name: 新增
        - code: SCMP004001002
          name: 编辑
        - code: SCMP004001002
          name: 禁用
      - code: SCMP004002
        name: 品牌管理
        link: '/product/brand'
        methods:
        - code: SCMP004002001
          name: 新增
        - code: SCMP004002002
          name: 编辑
        - code: SCMP004002003
          name: 禁用
      - code: SCMP004003
        name: SPU管理
        link: '/product/spu'
        methods:
        - code: SCMP004003001
          name: 新增
        - code: SCMP004003002
          name: 编辑
        - code: SCMP004003003
          name: 导出
      - code: SCMP004004
        name: SKU管理
        link: '/product/sku'
        methods:
        - code: SCMP004004001
          name: 新增
        - code: SCMP004004002
          name: 编辑
        - code: SCMP004004003
          name: 导入
        - code: SCMP004004004
          name: 待申请
        - code: SCMP004004005
          name: 审批跟踪
      - code: SCMP004005
        name: 销售区域配置
        link: '/product/saleArea'
      - code: SCMP004006
        name: 商品销售区域配置
        link: '/product/productSaleArea'
      - code: SCMP004007
        name: 配置信息管理
        link: '/product/productConfig'
        methods:
        - code: SCMP004007001
          name: 编辑
        - code: SCMP004007002
          name: 导入
      - code: SCMP004008
        name: 质检报告管理
        link: '/product/qualityReport'
        methods:
        - code: SCMP004008001
          name: 编辑
    - code: SCMP005
      name: 价格管理
      link: ''
      icon: icon-aq-jiage
      resources:
      - code: SCMP005001
        name: 价格查询
        link: '/price/price'
        methods:
        - code: SCMP005001001
          name: 新建变价
    - code: SCMP006
      name: 采购管理
      link: ''
      icon: icon-aq-caigou
      resources:
      - code: SCMP006001
        name: 采购申请单管理
        link: '/purchase/applyOrder'
        methods:
        - code: SCMP006001001
          name: 新增
        - code: SCMP006001002
          name: 编辑
        - code: SCMP006001003
          name: 生成采购单
      - code: SCMP006002
        name: 采购单管理
        link: '/purchase/purchase'
        methods:
        - code: SCMP006002001
          name: 取消
        - code: SCMP006002002
          name: 供应商备货
        - code: SCMP006002003
          name: 供应商发货
        - code: SCMP006002004
          name: 入库完成
        - code: SCMP006002005
          name: 仓储确认
      - code: SCMP006003
        name: 退供申请单管理
        link: '/purchase/refundApply'
        methods:
        - code: SCMP006003001
          name: 新增
        - code: SCMP006003002
          name: 编辑
        - code: SCMP006003003
          name: 生成退供单
      - code: SCMP006004
        name: 退供单管理
        link: '/purchase/refund'
        methods:
        - code: SCMP006004001
          name: 取消
        - code: SCMP006004002
          name: 供应商确认
        - code: SCMP006004003
          name: 发运
        - code: SCMP006004004
          name: 完成
    - code: SCMP007
      name: 销售管理
      link: ''
      icon: icon-aq-xiaoshou
      resources:
      - code: SCMP007001
        name: 订单管理
        link: '/sale/order'
      - code: SCMP007002
        name: 辅采订单管理
        link: '/sale/auxiliaryOrder'
      - code: SCMP007003
        name: 直送订单管理
        link: '/sale/directOrder'
      - code: SCMP007004
        name: 订单商品查询
        link: '/sale/orderProduct'
      - code: SCMP007005
        name: 商品唯一码查询
        link: '/sale/uniqueCode'
      - code: SCMP007006
        name: 退货管理
        link: '/sale/return'
      - code: SCMP007007
        name: 直送退货管理
        link: '/sale/directReturn'
      - code: SCMP007008
        name: 退货验货
        link: '/sale/returnInspection'
    - code: SCMP008
      name: 库存管理
      link: ''
      icon: icon-aq-kucun
      resources:
      - code: SCMP008001
        name: 中央库存管理
        link: '/inventory/totalInventory'
      - code: SCMP008002
        name: 仓库库存管理
        link: '/inventory/logisticsInventory'
      - code: SCMP008003
        name: 库房库存管理
        link: '/inventory/warehouseInventory'
      - code: SCMP008004
        name: 批次库存管理
        link: '/inventory/batchInventory'
    - code: SCMP009
      name: 库房管理
      link: ''
      icon: icon-aq-kufang
      resources:
      - code: SCMP009001
        name: 入库管理
        link: '/store/inStore'
      - code: SCMP009002
        name: 出库管理
        link: '/store/outStore'
      - code: SCMP009003
        name: 调拨管理
        link: '/store/transfer'
      - code: SCMP009004
        name: 移库管理
        link: '/store/move'
      - code: SCMP009005
        name: 报废管理
        link: '/store/scrap'
      - code: SCMP009006
        name: 损益管理
        link: '/store/profitLoss'
      - code: SCMP009007
        name: 供应商到货预约
        link: '/store/reservation'
      - code: SCMP009008
        name: 监管仓开单
        link: '/store/superviseOpen'
    - code: SCMP010
      name: 运输管理
      link: ''
      icon: icon-aq-yunshu
      resources:
      - code: SCMP010001
        name: 发运管理
        link: '/transport/shipment'
      - code: SCMP010002
        name: 运输管理
        link: '/transport/transport'
    - code: SCMP011
      name: 分析报表
      link: ''
      icon: icon-aq-fenxi
      resources:
      - code: SCMP011001
        name: 销售分析
        link: '/analysis/sale'
      - code: SCMP011002
        name: 月销售分析
        link: '/chart/monthSales'
      - code: SCMP011003
        name: 月毛利分析
        link: '/chart/monthGross'
      - code: SCMP011004
        name: 月销售达成率分析
        link: '/chart/monthSalesAchievement'
      - code: SCMP011005
        name: 月累计品类销售分析
        link: '/chart/MTDCategorySales'
      - code: SCMP011006
        name: 月累计品类毛利分析
        link: '/chart/MTDCategoryGross'
    - code: SCMP012
      name: 统计报表
      link: ''
      icon: icon-aq-tongji
      resources:
      - code: SCMP012001
        name: 供应商到货率统计-品采
        link: '/statistics/supplierArrival/BPDept'
      - code: SCMP012002
        name: 供应商到货率统计-辅采
        link: '/statistics/supplierArrival/APDept'
      - code: SCMP012003
        name: 供应商到货率统计-服纺
        link: '/statistics/supplierArrival/CTDept'
      - code: SCMP012004
        name: 供应商到货率统计-鞋品
        link: '/statistics/supplierArrival/FBDept'
      - code: SCMP012005
        name: 供应商到货率统计-自有品牌
        link: '/statistics/supplierArrival/PBDept'
      - code: SCMP012006
        name: 退供率统计-品采
        link: '/statistics/supplierReturn/BPDept'
      - code: SCMP012007
        name: 退供率统计-辅采
        link: '/statistics/supplierReturn/APDept'
      - code: SCMP012008
        name: 退供率统计-服纺
        link: '/statistics/supplierReturn/CTDept'
      - code: SCMP012009
        name: 退供率统计-鞋品
        link: '/statistics/supplierReturn/FBDept'
      - code: SCMP012010
        name: 退供率统计-自有品牌
        link: '/statistics/supplierReturn/PBDept'
      - code: SCMP012011
        name: 新品动销率统计-公司
        link: '/statistics/newGoodsInvoicing'
      - code: SCMP012012
        name: 新品动销率统计-品采
        link: '/statistics/newGoodsInvoicing/BPDept'
      - code: SCMP012013
        name: 新品动销率统计-辅采
        link: '/statistics/newGoodsInvoicing/APDept'
      - code: SCMP012014
        name: 新品动销率统计-服纺
        link: '/statistics/newGoodsInvoicing/CTDept'
      - code: SCMP012015
        name: 新品动销率统计-鞋品
        link: '/statistics/newGoodsInvoicing/FBDept'
      - code: SCMP012016
        name: 新品动销率统计-自有品牌
        link: '/statistics/newGoodsInvoicing/PBDept'
      - code: SCMP012017
        name: 门店复购率统计-公司
        link: '/statistics/storeRepurchase'
      - code: SCMP012018
        name: 门店复购率统计-品采
        link: '/statistics/storeRepurchase/BPDept'
      - code: SCMP012019
        name: 门店复购率统计-辅采
        link: '/statistics/storeRepurchase/APDept'
      - code: SCMP012020
        name: 门店复购率统计-服纺
        link: '/statistics/storeRepurchase/CTDept'
      - code: SCMP012021
        name: 门店复购率统计-鞋品
        link: '/statistics/storeRepurchase/FBDept'
      - code: SCMP012022
        name: 门店复购率统计-自有品牌
        link: '/statistics/storeRepurchase/PBDept'
      - code: SCMP012023
        name: 负毛利统计-公司
        link: '/statistics/nagativeGross'
      - code: SCMP012024
        name: 负毛利统计-品采
        link: '/statistics/nagativeGross/BPDept'
      - code: SCMP012025
        name: 负毛利统计-辅采
        link: '/statistics/nagativeGross/APDept'
      - code: SCMP012026
        name: 负毛利统计-服纺
        link: '/statistics/nagativeGross/CTDept'
      - code: SCMP012027
        name: 负毛利统计-鞋品
        link: '/statistics/nagativeGross/FBDept'
      - code: SCMP012028
        name: 负毛利统计-自有品牌
        link: '/statistics/nagativeGross/PBDept'
      - code: SCMP012029
        name: 销售统计-公司
        link: '/statistics/sale'
      - code: SCMP012030
        name: 销售统计-品采
        link: '/statistics/sale/BPDept'
      - code: SCMP012031
        name: 销售统计-辅采
        link: '/statistics/sale/APDept'
      - code: SCMP012032
        name: 销售统计-服纺
        link: '/statistics/sale/CTDept'
      - code: SCMP012033
        name: 销售统计-鞋品
        link: '/statistics/sale/FBDept'
      - code: SCMP012034
        name: 销售统计-自有品牌
        link: '/statistics/sale/PBDept'
      - code: SCMP012035
        name: 月累计销售统计-公司
        link: '/statistics/MTDCategorySale'
      - code: SCMP012036
        name: 月累计销售统计-品采
        link: '/statistics/MTDCategorySale/BPDept'
      - code: SCMP012037
        name: 月累计销售统计-辅采
        link: '/statistics/MTDCategorySale/APDept'
      - code: SCMP012038
        name: 月累计销售统计-服纺
        link: '/statistics/MTDCategorySale/CTDept'
      - code: SCMP012039
        name: 月累计销售统计-鞋品
        link: '/statistics/MTDCategorySale/FBDept'
      - code: SCMP012040
        name: 月累计销售统计-自有品牌
        link: '/statistics/MTDCategorySale/PBDept'
      - code: SCMP012041
        name: 低库存统计-公司
        link: '/statistics/lowInventory'
      - code: SCMP012042
        name: 低库存统计-品采
        link: '/statistics/lowInventory/BPDept'
      - code: SCMP012043
        name: 低库存统计-辅采
        link: '/statistics/lowInventory/APDept'
      - code: SCMP012044
        name: 低库存统计-服纺
        link: '/statistics/lowInventory/CTDept'
      - code: SCMP012045
        name: 低库存统计-鞋品
        link: '/statistics/lowInventory/FBDept'
      - code: SCMP012046
        name: 低库存统计-自有品牌
        link: '/statistics/lowInventory/PBDept'
      - code: SCMP012047
        name: 高库存统计-公司
        link: '/statistics/highInventory'
      - code: SCMP012048
        name: 高库存统计-品采
        link: '/statistics/highInventory/BPDept'
      - code: SCMP012049
        name: 高库存统计-辅采
        link: '/statistics/highInventory/APDept'
      - code: SCMP012050
        name: 高库存统计-服纺
        link: '/statistics/highInventory/CTDept'
      - code: SCMP012051
        name: 高库存统计-鞋品
        link: '/statistics/highInventory/FBDept'
      - code: SCMP012052
        name: 高库存统计-自有品牌
        link: '/statistics/highInventory/PBDept'
      - code: SCMP012053
        name: 品类促销统计-公司
        link: '/statistics/categoryPromotion'
      - code: SCMP012054
        name: 品类促销统计-品采
        link: '/statistics/categoryPromotion/BPDept'
      - code: SCMP012055
        name: 品类促销统计-辅采
        link: '/statistics/categoryPromotion/APDept'
      - code: SCMP012056
        name: 品类促销统计-服纺
        link: '/statistics/categoryPromotion/CTDept'
      - code: SCMP012057
        name: 品类促销统计-鞋品
        link: '/statistics/categoryPromotion/FBDept'
      - code: SCMP012058
        name: 品类促销统计-自有品牌
        link: '/statistics/categoryPromotion/PBDept'
      - code: SCMP012059
        name: 缺货统计-公司
        link: '/statistics/stockout'
      - code: SCMP012060
        name: 缺货统计-品采
        link: '/statistics/stockout/BPDept'
      - code: SCMP012061
        name: 缺货统计-辅采
        link: '/statistics/stockout/APDept'
      - code: SCMP012062
        name: 缺货统计-服纺
        link: '/statistics/stockout/CTDept'
      - code: SCMP012063
        name: 缺货统计-鞋品
        link: '/statistics/stockout/FBDept'
      - code: SCMP012064
        name: 缺货统计-自有品牌
        link: '/statistics/stockout/PBDept'
      - code: SCMP012065
        name: 品类销售统计-OEM
        link: '/statistics/categorySale/PBDept'
      - code: SCMP012066
        name: 品牌销售统计-OEM
        link: '/statistics/brandSale/PBDept'
    - code: SCMP013
      name: 查询报表
      link: ''
      icon: icon-aq-chaxun
      resources:
      - code: SCMP013001
        name: 供应商到货率查询
        link: '/query/supplierArrival'
      - code: SCMP013002
        name: 商品进销存查询
        link: '/query/goodsInvoicing'
      - code: SCMP013003
        name: 赠品进销存查询
        link: '/query/presentInvoicing'
      - code: SCMP013004
        name: 退供查询
        link: '/query/supplierReturn'
      - code: SCMP013005
        name: 新品动销查询
        link: '/query/newGoodsPinRate'
      - code: SCMP013006
        name: 门店复购率查询
        link: '/query/storeRepurchase'
      - code: SCMP013007
        name: 负毛利查询
        link: '/query/nagativeGross'
      - code: SCMP013008
        name: 建议补货查询
        link: '/query/suggestReplenish'
      - code: SCMP013009
        name: 品牌促销查询
        link: '/query/brandPromotion'
      - code: SCMP013010
        name: 品类促销查询
        link: '/query/categoryPromotion'
      - code: SCMP013011
        name: 月销售查询
        link: '/query/monthSales'
      - code: SCMP013012
        name: 月累计品类销售查询
        link: '/query/MTDCategorySales'
      - code: SCMP013013
        name: 商品销售查询
        link: '/query/goodsSale'
      - code: SCMP013014
        name: 库存周转查询
        link: '/query/inventoryTurnover'
      - code: SCMP013015
        name: 库存在途周转查询
        link: '/query/inventoryTurnoverWay'