spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3600000
server:
   tomcat:
     basedir: /tmp/dir
web:
  host-url: http://scmp.bms.aiqin.com
center:
  main:
  #中控服务端
    url: http://control.api.aiqin.com
  #中控前端
    host: http://control.mgs.aiqin.com
product:
  info:
    url: http://com.aiqin.bms.scmp.api.api.aiqin.com
wms:
  url: http://abutment.api.aiqin.com
ground:
  druid:
    url: jdbc:mysql://39.96.85.170:3306/bms_scmp?connectTimeout=5000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: scmp_write
    password: nCUdR4jBQPVnSDVTSxFaA
    initial-size: 5
    min-idle: 3
    max-active: 20
    max-wait: 6000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters: stat,slf4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.map,/druid/*"
      session-stat-enable: false
      profile-enable: true
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: false
      login-password: druid
      login-username: druid
      allow: 127.0.0.1,192.168.0.0/16,172.16.0.0/16

oss:
  end:
    point: http://oss-cn-beijing.aliyuncs.com
  access:
    key:
      id: LTAILR1FRNY70UY0
      secret: OWTAtojGLNLbcmGGGsOWE7AC9UguvU
  bucket:
    name: aq-flows-test
  dir: dev/
Encryption:
#  key: 16#t%9@AJ6DYaeRp
  key: dZ3@k!KMhq!Tqeh3%RYm83cX&JmvYyY!
UserName:
  key: 11921
CurrentPositionCode:
  key: GW0317
evn: test
