server:
   tomcat:
     basedir: /tmp/dir
web:
  host-url: http://scmp.bms.aiqin.com
center:
  main:
  #中控服务端
    url: http://control.api.aiqin.com
  #中控前端
    host: http://control.mgs.aiqin.com
control:
  url:
   # 角色列表
    role-list: http://127.0.1:9090/role/list
    # 角色绑定
    role-add: http://127.0.1:9090/person/account/role
   # 主控增加人员等接口
    account: http://127.0.1:9090/external/account
product:
  info:
    url: http://com.aiqin.bms.scmp.api.api.aiqin.com
ground:
  druid:
    url: jdbc:mysql://39.96.85.170:3306/bms_scmp?connectTimeout=5000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: scmp_write
    password: nCUdR4jBQPVnSDVTSxFaA
    initialSize: 5
    minIdle: 3
    maxActive: 40
    maxWait: 6000000
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
    filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50000
    web-stat-filter:
      enabled: true
      url-pattern: /*
#      exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,*.map,/druid/*
      session-stat-enable: false
      profile-enable: true
oss:
  end:
    point: http://oss-cn-beijing.aliyuncs.com
  access:
    key:
      id: LTAILR1FRNY70UY0
      secret: OWTAtojGLNLbcmGGGsOWE7AC9UguvU
  bucket:
    name: aq-flows-test
  dir: dev/
Encryption:
#  key: 16#t%9@AJ6DYaeRp
  key: dZ3@k!KMhq!Tqeh3%RYm83cX&JmvYyY!
UserName:
  key: 11921
CurrentPositionCode:
  key: GW0317
evn: test
