server:
    port: 80
#    tomcat:
#      basedir: /tmp/dir
spring:
    profiles:
        active: ${profile.name}
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    swagger:
        enabled: true
        title: SUPPLIER-API
        description: 熙耘供应链系统的API文档
        version: 1.0.0
        contact:
            name: liuxiaohan
        base-package: com.aiqin.bms.scmp.api.webSwagger2Config
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 20MB
mybatis:
    mapper-locations: classpath*:/com/aiqin/bms/scmp/api/*/dao/*.xml,classpath*:/com/aiqin/bms/scmp/api/*/mapper/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.aiqin.bms.scmp.api.*.domain
    configuration:
      call-setters-on-nulls: true
logging:
    config: classpath:logback.xml
    level:
        io.swagger.models.parameters.AbstractSerializableParameter: error
image:
  upload:
    path: D:\\images\\
marker:
  info:
    url: http://market.api.aiqin.com/
Central:
    url: http://control.api.aiqin.com
Store:
  url: http://store.api.aiqin.com
Workflow:
    url: http://finance.bms.aiqin.com/tpm/workflowcontroller/submit
    cancelUrl: http://finance.bms.aiqin.com/tpm/workflowcontroller/cancel
#审批流的前缀url地址
WorkFlowBaseUrl:
    #回调url
    callBackBaseUrl: http://scmp.api.aiqin.com/workFlow/workFlowCallBack/
  #各个页面详情url
    supplierUrl:
        #合同申请详情
        applyContract: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
        #供应商申请详情
        applySupplier: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
        #供应商集团申请详情
        applySupplierGroup: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess
        #供应商账户申请详情
        applySupplierAccount: http://scmp.bms.aiqin.com/#/supplier/detailSupplierApprovalProcess


        #制造商申请详情
        applyManu: http://scmp.bms.aiqin.com/#/Supplier/ManuApplieDetail/
        #采购申请详情
        applyPurchase: http://scmp.bms.aiqin.com/#/purchase/detailPurchase
        #退供申请详情
        applyRefund: http://scmp.bms.aiqin.com/#/purchase/returnDetail
        #调拨申请详情
        applyAllocattion: http://scmp.bms.aiqin.com/#/Supplier/AllocattionDetail/
        #商品申请详情
        applyGoods: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
        #商品配置申请详情
        applyGoodsConfig: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
        #商品价格申请详情
        applyGoodsPrice:
    productUrl:
      #/Supplier/IntendingDetails?variablePriceName=促销活动&priceTypeCode=1&variablePriceCode=10001
      variablePrice: http://scmp.bms.aiqin.com/#/Supplier/IntendingDetails
      applySku: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
      applySkuConfig: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
      #销售区域
      applySaleArea: http://scmp.bms.aiqin.com/#/product/detailProductApprovalProcess
      #调拨申请详情
      applyAllocattion: http://scmp.bms.aiqin.com/#/Supplier/AllocattionDetail/
      #移库查看详情
      movement: http://scmp.bms.aiqin.com/#/Supplier/MoveWareHouseDetail
#审批流的host
WorkFlowBaseHost:
    supplierHost: http://scmp.bms.aiqin.com
#不拦截的公参
BaseParam:
    authority: authority=0
WMS:
  url: http://39.96.81.67:9003
order:
  info:
    url: http://order.api.aiqin.com/
mgs:
    control:
        system-code: scmp-system
        center: http://control.api.aiqin.com/system/plan
        resources:
        - code: SCMP001
          name: 基础资料管理
          link: ''
          icon: icon-scm-ziliao
          resources:
          - code: SCMP001001
            name: 字典管理
            link: '/Supplier/TheDictionary'
            icon: fa-home
            methods:
            - code: SCMP001001001
              name: 查询
            - code: SCMP001001002
              name: 增加
          - code: SCMP001002
            name: 采购组管理
            link: '/Supplier/PurchasingGroup'
            icon: fa-home
            methods:
            - code: SCMP001002001
              name: 查询
            - code: SCMP001002002
              name: 增加
          - code: SCMP001003
            name: 仓库管理
            link: '/Supplier/BasedLogistics'
            icon: fa-home
            methods:
            - code: SCMP001003001
              name: 查询
            - code: SCMP001003002
              name: 增加
          - code: SCMP001004
            name: 库房管理
            link: '/Supplier/BasedWarehouse'
            icon: fa-home
            methods:
            - code: SCMP001004001
              name: 查询
            - code: SCMP001004002
              name: 增加
          - code: SCMP001005
            name: 价格项目管理
            link: '/Supplier/PriceProject'
            icon: fa-home
            methods:
            - code: SCMP001005001
              name: 查询
            - code: SCMP001005002
              name: 增加
          - code: SCMP001006
            name: 渠道管理
            link: '/Supplier/ChannelManagement'
            icon: fa-home
            methods:
            - code: SCMP001006001
              name: 查询
            - code: SCMP001006002
              name: 增加
          - code: SCMP001007
            name: 标签管理
            link: '/Supplier/LabelManagement'
            icon: fa-home
            methods:
            - code: SCMP001007001
              name: 查询
            - code: SCMP001007002
              name: 增加
        - code: SCMP003
          name: 供应商管理
          link: ''
          icon: icon-scm-scmp
          resources:
          - code: SCMP003001
            name: 供应商管理
            link: '/Supplier/SupManage'
            icon: fa-home
            methods:
            - code: SCMP003001001
              name: 查询
            - code: SCMP003001002
              name: 增加
          - code: SCMP003002
            name: 供应商集团管理
            link: '/Supplier/SupplierGroupManagement'
            icon: fa-home
            methods:
            - code: SCMP003002001
              name: 查询
          - code: SCMP003003
            name: 账户管理
            link: '/Supplier/SupUnitAccountManage'
            icon: fa-home
            methods:
            - code: SCMP003003001
              name: 查询
            - code: SCMP003003002
              name: 增加
          - code: SCMP003004
            name: 供应商申请管理
            link: '/Supplier/SupApplicationManage'
            icon: fa-home
            methods:
            - code: SCMP003004001
              name: 查询
          - code: SCMP003007
            name: 合同管理
            link: '/Supplier/ContractManage'
            icon: fa-home
            methods:
            - code: SCMP003007001
              name: 查询
            - code: SCMP003007002
              name: 增加
          - code: SCMP003009
            name: 制造商管理
            link: '/Supplier/SupManuManage'
            icon: fa-home
            methods:
            - code: SCMP003009001
              name: 查询
            - code: SCMP003009002
              name: 增加
        - code: SCMP002
          name: 商品管理
          link: ''
          icon: icon-scm-shangpin
          resources:
          - code: SCMP002001
            name: 品类管理
            link: '/Supplier/Category'
            icon: fa-home
            methods:
            - code: SCMP002001001
              name: 新增
            - code: SCMP002001002
              name: 显示启用
            - code: SCMP002001003
              name: 显示全部
          - code: SCMP002002
            name: 品牌管理
            link: '/Supplier/Brand'
            icon: fa-home
            methods:
            - code: SCMP002002001
              name: 查询
            - code: SCMP002002002
              name: 增加
          - code: SCMP002003
            name: 商品管理
            link: '/Supplier/CommodityManagement'
            icon: fa-home
            methods:
            - code: SCMP002003001
              name: 查询
            - code: SCMP002003002
              name: 增加
          - code: SCMP002004
            name: SKU管理
            link: '/Supplier/SkuManagement'
            icon: fa-home
            methods:
            - code: SCMP002004001
              name: 查询
            - code: SCMP002004002
              name: 增加
          - code: SCMP002005
            name: 商品申请管理
            link: '/Supplier/GoodsApplyManage'
            icon: fa-home
            methods:
            - code: SCMP002005001
              name: 查询
            - code: SCMP002005002
              name: 增加
          - code: SCMP002006
            name: 商品配置管理
            link: '/Supplier/GoodsConfiguration'
            icon: fa-home
            methods:
            - code: SCMP002006001
              name: 查询
            - code: SCMP002006002
              name: 增加
          - code: SCMP002007
            name: 商品配置申请管理
            link: '/Supplier/GoodsConfigurationApp'
            icon: fa-home
            methods:
            - code: SCMP002007001
              name: 查询
        - code: SCMP007
          name: 价格管理
          link: ''
          icon: icon-scm-price1
          resources:
          - code: SCMP007001
            name: 价格管理
            link: '/Supplier/PriceManagement'
            icon: fa-home
            methods:
            - code: SCMP007001001
              name: 查询
          - code: SCMP007002
            name: 变价管理
            link: '/Supplier/IntendingManagement'
            icon: fa-home
            methods:
            - code: SCMP007001001
              name: 查询
            - code: SCMP007001002
              name: 增加
        - code: SCMP004
          name: 库存管理
          link: ''
          icon: icon-scm-kucun
          resources:
          - code: SCMP004001
            name: 总库存管理
            link: '/Supplier/InvGeneralManage'
            icon: fa-home
            methods:
            - code: SCMP004001001
              name: 查询
          - code: SCMP004002
            name: 物流中心库存管理
            link: '/Supplier/InvDistributeCenterManage'
            icon: fa-home
            methods:
            - code: SCMP004002001
              name: 查询
          - code: SCMP004003
            name: 库房库存管理
            link: '/Supplier/InvWarehouseManage'
            icon: fa-home
            methods:
            - code: SCMP004003001
              name: 查询
        - code: SCMP005
          name: 采购管理
          link: ''
          icon: icon-scm-caigou
          resources:
          - code: SCMP005003
            name: 采购商品
            link: '/Supplier/PurchasingGoods'
            icon: fa-home
            methods:
            - code: SCMP005003001
              name: 查询
          - code: SCMP005004
            name: 采购申请
            link: '/Supplier/PurchasingApply'
            icon: fa-home
            methods:
            - code: SCMP005004001
              name: 查询
            - code: SCMP005004002
              name: 采购对比
            - code: SCMP005004003
              name: 申请采购
          - code: SCMP005001
            name: 采购管理
            link: '/Supplier/PurchasingSupplyManagement'
            icon: fa-home
            methods:
            - code: SCMP005001001
              name: 查询
            - code: SCMP005001002
              name: 增加
          - code: SCMP005002
            name: 退供管理
            link: '/Supplier/RefundManagement'
            icon: fa-home
            methods:
            - code: SCMP005002001
              name: 查询
            - code: SCMP005002002
              name: 增加
        - code: SCMP006
          name: 销售管理
          link: ''
          icon: icon-scm-xiaoshou
          resources:
          - code: SCMP006001
            name: 订单管理
            link: '/Supplier/OrderManage'
            icon: fa-home
            methods:
            - code: SCMP006001001
              name: 查询
          - code: SCMP006002
            name: 退货管理
            link: '/Supplier/RefundGoodsManage'
            icon: fa-home
            methods:
            - code: SCMP006002001
              name: 查询
        - code: SCMP008
          name: 库房管理
          link: ''
          icon: icon-scm-kufang
          resources:
          - code: SCMP008001
            name: 入库管理
            link: '/Supplier/StoreManageIn'
            icon: fa-home
            methods:
            - code: SCMP008001001
              name: 查询
          - code: SCMP008002
            name: 出库管理
            link: '/Supplier/StoreManageOut'
            icon: fa-home
            methods:
            - code: SCMP008002001
              name: 查询
          - code: SCMP008003
            name: 调拨管理
            link: '/Supplier/AllocattionManage'
            icon: fa-home
            methods:
            - code: SCMP005003001
              name: 查询
            - code: SCMP005003002
              name: 增加
          - code: SCMP008004
            name: 移库管理
            link: '/Supplier/MoveLibraryManage'
            icon: fa-home
            methods:
            - code: SCMP005004001
              name: 查询
            - code: SCMP005005002
              name: 增加
        - code: SCMP009
          name: 运输管理
          link: ''
          icon: icon-scm-kufang
          resources:
          - code: SCMP009001
            name: 发运管理
            link: '/Supplier/ShipManagement'
            icon: fa-home
            methods:
            - code: SCMP009001001
              name: 查询
            - code: SCMP009001002
              name: 新增
          - code: SCMP009002
            name: 运输管理
            link: '/Supplier/TransportationManagement'
            icon: fa-home
            methods:
            - code: SCMP009002001
              name: 查询
            - code: SCMP009002002
              name: 新增